version: '3'
dotenv: ['.env']
tasks:
  default:
    cmds:
      - task: dev:api

  # -
  # Run development related tasks
  # -
  dev:api:
    dir: pkg/api
    cmds:
      - yarn workspace api run watch

  dev:fe:
    dir: pkg/frontend
    cmds:
      - yarn workspace frontend run start

  dev:adm:
    dir: pkg/admin
    cmds:
      - yarn workspace admin run start

  dev:compose:
    cmds:
      - docker-compose up -d
      - docker-compose logs -f petio

  # -
  # Run app
  # -
  run:api:
    cmds:
      - yarn workspace api run start

  # -
  # Debug/Benchmark/Analysis app
  # -
  debug:api:
    cmds:
      - yarn workspace api run clinic

  # -
  # Run build related tasks
  # -
  build:
    deps: ['build:pre']
    cmds:
      - task: build:fe
      - task: build:api:prod

  build:pre:
    cmds:
      - yarn workspaces focus --all

  build:fe:
    dir: pkg/frontend
    cmds:
      - yarn workspace frontend run build

  build:api:
    dir: pkg/api
    cmds:
      - yarn workspace api run build

  build:api:prod:
    dir: pkg/api
    cmds:
      - yarn workspace api run build:prod

  # -
  # Generate
  # -
  generate:
    cmds:
      - yarn dlx prisma generate

  # -
  # Package
  # -
  pkg:
    deps:
      - 'build:pre'
      - 'build:fe'
      - 'build:api:prod'
    cmds:
      - yarn run release

  pkg:docker:
    dir: pkg/api
    cmds:
      - pkg --targets node16-alpine-x64 --public-packages "*" --output ../../releases/petio-alpine-x64 ./main.js

  # -
  # Docker
  # -
  # Build the image itself
  docker:build:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_REPO}}:local .
    env:
      DOCKER_BUILDKIT: 1

  # Publish the hash of the image
  docker:hash:
    deps: ['docker:build']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:{{.DOCKER_IMAGE_REPO_VERSION}}
      - docker push {{.DOCKER_IMAGE_REPO}}:{{.DOCKER_IMAGE_REPO_VERSION}}
    vars:
      DOCKER_IMAGE_REPO_VERSION:
        sh: git log -1 --format=%H

  # Publish the new-ui image
  docker:new-ui:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:new-ui
      - docker push {{.DOCKER_IMAGE_REPO}}:new-ui

  # Publish the nightly image
  docker:nightly:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:nightly
      - docker push {{.DOCKER_IMAGE_REPO}}:nightly

  # Publish the preview image
  docker:preview:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:preview
      - docker push {{.DOCKER_IMAGE_REPO}}:preview

  # Publish the latest image
  docker:latest:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:latest
      - docker push {{.DOCKER_IMAGE_REPO}}:latest

  # -
  # Release
  # -
  release:
    dir: pkg/api
    cmds:
      - yarn dlx semantic-release --extends ../../semantic-release.json --dry-run --no-ci

  release:prepare:
    cmds:
      - task: pkg
      - task: docker:latest

  release:ci:
    dir: pkg/api
    cmds:
      - yarn dlx semantic-release --extends ../../semantic-release.json

# Global Vars
vars:
  DOCKER_IMAGE_REPO: ghcr.io/petio-team/petio
