version: '3'
dotenv: ['.env']
vars:
  COMMIT_SHA: {sh: 'git rev-parse --short HEAD'}
tasks:
  default:
    cmds:
      - task: dev:server

  build:
    cmds:
      - yarn workspaces focus --all
      - yarn workspace web run build
      - yarn workspace server run build

  build:prod:
    cmds:
      - yarn workspaces focus --all
      - yarn workspace web run build:prod
      - yarn workspace server run build:prod

  dev:binary:
    dir: ./dist/binaries
    cmds:
      - ./petio-alpine-x64

  dev:local:
    cmds:
      - task: build:prod
      - yarn run pkg
      - task: dev:binary


  dev:server:
    cmds:
      - yarn workspace server run watch

  dev:web:
    cmds:
      - yarn workspace web run start

  ci:
    cmds:
      - earthly +build-all --COMMIT_SHA={{ .COMMIT_SHA }} --LABEL=nightly
