version: '3'
dotenv: ['.env']
tasks:
  default:
    cmds:
      - task: dev:api

  build:
    cmds:
      - yarn workspaces focus --all
      - yarn workspace frontend run build
      - yarn workspace api run build
