version: '3'
dotenv: ['.env']
tasks:
  # -
  # Run CI related tasks
  # -
  ci:
    cmds:
      - npm ci

  # -
  # Run development related tasks
  # -
  dev:
    dir: pkg/api
    cmds:
      -  node-dev ./main.ts

  dev:compose:
    cmds:
      - docker-compose up -d
      - docker-compose logs -f petio

  # -
  # Run build related tasks
  # -
  build:
    deps: [
      'build:frontend',
      'build:api'
    ]

  build:frontend:
    dir: pkg/frontend
    cmds:
      - npm install
      - npm run build

  build:api:
    dir: pkg/api
    cmds:
      - npm install --legacy-peer-deps
      - npm run build

  # -
  # Package
  # -
  pkg:
    dir: pkg/api
    cmds:
      - pkg . --no-bytecode --public-packages "*"

  pkg:docker:
    dir: pkg/api
    cmds:
      - pkg --targets node16-alpine-x64 --public-packages "*" --output ../../releases/petio-alpine-x64 ./main.js

  # -
  # Docker
  # -
  # Build the image itself
  docker:build:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_REPO}}:local .
    env:
      DOCKER_BUILDKIT: 1

  # Publish the hash of the image
  docker:hash:
    deps: ['docker:build']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:{{.DOCKER_IMAGE_REPO_VERSION}}
      - docker push {{.DOCKER_IMAGE_REPO}}:{{.DOCKER_IMAGE_REPO_VERSION}}
    vars:
      DOCKER_IMAGE_REPO_VERSION:
        sh: git log -1 --format=%H

  # Publish the new-ui image
  docker:new-ui:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:new-ui
      - docker push {{.DOCKER_IMAGE_REPO}}:new-ui

  # Publish the nightly image
  docker:nightly:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:nightly
      - docker push {{.DOCKER_IMAGE_REPO}}:nightly

  # Publish the preview image
  docker:preview:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:preview
      - docker push {{.DOCKER_IMAGE_REPO}}:preview

  # Publish the latest image
  docker:latest:
    deps: ['docker:hash']
    cmds:
      - docker tag {{.DOCKER_IMAGE_REPO}}:local {{.DOCKER_IMAGE_REPO}}:latest
      - docker push {{.DOCKER_IMAGE_REPO}}:latest

  # -
  # Release
  # -
  release:
    dir: pkg/api
    cmds:
      - npx semantic-release --extends ../../semantic-release.json --dry-run --no-ci

  release:prepare:
    cmds:
      - task: pkg
      - task: docker:latest

  release:ci:
    dir: pkg/api
    cmds:
      - npx semantic-release --extends ../../semantic-release.json

# Global Vars
vars:
  DOCKER_IMAGE_REPO: ghcr.io/petio-team/petio