export enum SortByType {
  PopularityASC = 'popularity.asc',
  PopularityDESC = 'popularity.desc',
  ReleaseDateASC = 'release_date.asc',
  ReleaseDateDESC = 'release_date.desc',
  RevenueASC = 'revenue.asc',
  RevenueDESC = 'revenue.desc',
  PrimaryReleaseDateASC = 'primary_release_date.asc',
  PrimaryReleaseDateDESC = 'primary_release_date.desc',
  OriginalTitleASC = 'original_title.asc',
  OriginalTitleDESC = 'original_title.desc',
  VoteAverageASC = 'vote_average.asc',
  VoteAverageDESC = 'vote_average.desc',
  VoteCountASC = 'vote_count.asc',
  VoteCountDESC = 'vote_count.desc',
}
