export const ARGUMENT_INVALID = 'ARGUMENT_INVALID';
export const ARGUMENT_OUT_OF_RANGE = 'ARGUMENT_OUT_OF_RANGE';
export const ARGUMENT_NOT_PROVIDED = 'ARGUMENT_NOT_PROVIDED';
export const NOT_FOUND = 'NOT_FOUND';
export const CONFLICT = 'CONFLICT';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
