name: Docker Master Build

on:
  push:
    branches:
      - master
jobs:
  docker-aio:
    name: Docker Master Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:latest-${GITHUB_SHA::8} .
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io
      - name: Push docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
